/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VerificationRollingWindow = IDL.Variant({
  'last3Games' : IDL.Null,
  'seasonAverage' : IDL.Null,
});
export const SensitivitySettings = IDL.Record({
  'marketAlertsEnabled' : IDL.Bool,
  'edgeThresholdPercentage' : IDL.Nat,
  'verificationRollingWindow' : VerificationRollingWindow,
});
export const UserProfile = IDL.Record({
  'notificationPreferences' : IDL.Bool,
  'name' : IDL.Text,
  'sensitivitySettings' : SensitivitySettings,
  'favoriteTeams' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Sport = IDL.Variant({
  'mlb' : IDL.Null,
  'nba' : IDL.Null,
  'nfl' : IDL.Null,
});
export const CoachRatingD = IDL.Record({
  'name' : IDL.Text,
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'sport' : Sport,
  'coachID' : IDL.Nat,
  'defensiveRating' : IDL.Float64,
  'lineupAdjustments' : IDL.Text,
});
export const EdgeCalculation = IDL.Record({
  'edgePercentage' : IDL.Float64,
  'calcTime' : Time,
  'propId' : IDL.Nat,
  'edgeScore' : IDL.Text,
  'isValid' : IDL.Bool,
});
export const GameStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const LineType = IDL.Variant({
  'prizePicks' : IDL.Null,
  'sportsBook' : IDL.Null,
});
export const PropType = IDL.Variant({
  'playerRebounds' : IDL.Null,
  'playerPassingYards' : IDL.Null,
  'playerAssists' : IDL.Null,
  'playerPoints' : IDL.Null,
});
export const StatCategory = IDL.Variant({
  'assists' : IDL.Null,
  'rebounds' : IDL.Null,
  'passingYards' : IDL.Null,
  'points' : IDL.Null,
  'passesCompleted' : IDL.Null,
});
export const LivePick = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'line' : IDL.Float64,
  'gameStatus' : GameStatus,
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'tournament' : IDL.Text,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'awayMoneylineOdds' : IDL.Opt(IDL.Float64),
  'playerName' : IDL.Text,
  'homeMoneylineOdds' : IDL.Opt(IDL.Float64),
  'lineString' : IDL.Text,
  'statCategory' : StatCategory,
});
export const LivePicksDiagnostics = IDL.Record({
  'lastFailureMessage' : IDL.Text,
  'totalFailures' : IDL.Nat,
  'lastSuccess' : Time,
  'totalAttempts' : IDL.Nat,
  'lastFailure' : Time,
  'totalSuccesses' : IDL.Nat,
  'lastAttempt' : Time,
  'numLivePicks' : IDL.Nat,
});
export const PlayerProps = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'line' : IDL.Float64,
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'tournament' : IDL.Text,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'playerName' : IDL.Text,
  'lineString' : IDL.Text,
  'statCategory' : StatCategory,
});
export const ProjectionType = IDL.Variant({
  'userCustom' : IDL.Null,
  'algoGenerated' : IDL.Null,
});
export const Projection = IDL.Record({
  'value' : IDL.Float64,
  'calcTime' : Time,
  'projectionType' : ProjectionType,
  'propId' : IDL.Nat,
  'isValid' : IDL.Bool,
});
export const VerificationResult = IDL.Record({
  'verificationTime' : Time,
  'verificationSummary' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'propId' : IDL.Nat,
});
export const PlayerPropsWithEdgesView = IDL.Record({
  'projections' : IDL.Vec(Projection),
  'verificationResults' : IDL.Vec(VerificationResult),
  'prop' : PlayerProps,
  'edges' : IDL.Vec(EdgeCalculation),
});
export const IngestionProviderConfig = IDL.Record({
  'oddsApiKey' : IDL.Text,
  'opticOddsApiKey' : IDL.Text,
  'dailyFantasyApiKey' : IDL.Text,
});
export const SettlementStatus = IDL.Variant({
  'active' : IDL.Null,
  'settled' : IDL.Null,
});
export const SettlementOutcome = IDL.Variant({
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'push' : IDL.Null,
});
export const SettleablePrediction = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'betAmount' : IDL.Opt(IDL.Float64),
  'line' : IDL.Float64,
  'gameStatus' : GameStatus,
  'odds' : IDL.Opt(IDL.Float64),
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'tournament' : IDL.Text,
  'settlementStatus' : SettlementStatus,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'playerName' : IDL.Text,
  'resultValue' : IDL.Opt(IDL.Float64),
  'outcome' : IDL.Opt(SettlementOutcome),
  'lineString' : IDL.Text,
  'statCategory' : StatCategory,
});
export const SettlementDiagnostics = IDL.Record({
  'totalSettledPredictions' : IDL.Nat,
  'lastFailureMessage' : IDL.Text,
  'totalFailedSettlements' : IDL.Nat,
  'totalSettlementAttempts' : IDL.Nat,
  'lastSuccess' : Time,
  'numSettledInLastRun' : IDL.Nat,
  'totalPendingPredictions' : IDL.Nat,
  'lastFailure' : Time,
  'lastAttempt' : Time,
  'totalSuccessfulSettlements' : IDL.Nat,
});
export const SettlementMetrics = IDL.Record({
  'totalLost' : IDL.Nat,
  'totalPush' : IDL.Nat,
  'totalROI' : IDL.Float64,
  'totalWon' : IDL.Nat,
  'totalSettled' : IDL.Nat,
  'sevenDayWinRate' : IDL.Float64,
});
export const OpticOddsConnectionResult = IDL.Record({
  'healthy' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'statusCode' : IDL.Opt(IDL.Nat),
  'responseBody' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActivePredictionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachRating' : IDL.Func([IDL.Nat], [IDL.Opt(CoachRatingD)], ['query']),
  'getEdgesSorted' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(EdgeCalculation)],
      ['query'],
    ),
  'getLivePicks' : IDL.Func([], [IDL.Vec(LivePick)], ['query']),
  'getLivePicksDiagnostics' : IDL.Func([], [LivePicksDiagnostics], ['query']),
  'getLivePicksLastUpdated' : IDL.Func([], [Time], ['query']),
  'getNBAPlayerProps' : IDL.Func([], [IDL.Vec(PlayerProps)], ['query']),
  'getPlayerProp' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerProps)], ['query']),
  'getPlayerPropsWithEdges' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerPropsWithEdgesView)],
      ['query'],
    ),
  'getProjection' : IDL.Func([IDL.Nat], [IDL.Opt(Projection)], ['query']),
  'getProviderConfig' : IDL.Func(
      [],
      [IDL.Opt(IngestionProviderConfig)],
      ['query'],
    ),
  'getSettleablePrediction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SettleablePrediction)],
      ['query'],
    ),
  'getSettlementDiagnostics' : IDL.Func([], [SettlementDiagnostics], ['query']),
  'getSettlementMetrics' : IDL.Func([], [SettlementMetrics], ['query']),
  'getSource' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSensitivitySettings' : IDL.Func(
      [],
      [IDL.Opt(SensitivitySettings)],
      ['query'],
    ),
  'getVerificationResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(VerificationResult)],
      ['query'],
    ),
  'importData' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshLivePicksInternal' : IDL.Func([], [], []),
  'register' : IDL.Func([], [], []),
  'runSettlementNow' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOrUpdateProp' : IDL.Func([PlayerProps], [], []),
  'saveProviderConfig' : IDL.Func([IngestionProviderConfig], [], []),
  'testOpticOddsConnection' : IDL.Func([], [OpticOddsConnectionResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSensitivitySettings' : IDL.Func([SensitivitySettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VerificationRollingWindow = IDL.Variant({
    'last3Games' : IDL.Null,
    'seasonAverage' : IDL.Null,
  });
  const SensitivitySettings = IDL.Record({
    'marketAlertsEnabled' : IDL.Bool,
    'edgeThresholdPercentage' : IDL.Nat,
    'verificationRollingWindow' : VerificationRollingWindow,
  });
  const UserProfile = IDL.Record({
    'notificationPreferences' : IDL.Bool,
    'name' : IDL.Text,
    'sensitivitySettings' : SensitivitySettings,
    'favoriteTeams' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Sport = IDL.Variant({
    'mlb' : IDL.Null,
    'nba' : IDL.Null,
    'nfl' : IDL.Null,
  });
  const CoachRatingD = IDL.Record({
    'name' : IDL.Text,
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'sport' : Sport,
    'coachID' : IDL.Nat,
    'defensiveRating' : IDL.Float64,
    'lineupAdjustments' : IDL.Text,
  });
  const EdgeCalculation = IDL.Record({
    'edgePercentage' : IDL.Float64,
    'calcTime' : Time,
    'propId' : IDL.Nat,
    'edgeScore' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  const GameStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const LineType = IDL.Variant({
    'prizePicks' : IDL.Null,
    'sportsBook' : IDL.Null,
  });
  const PropType = IDL.Variant({
    'playerRebounds' : IDL.Null,
    'playerPassingYards' : IDL.Null,
    'playerAssists' : IDL.Null,
    'playerPoints' : IDL.Null,
  });
  const StatCategory = IDL.Variant({
    'assists' : IDL.Null,
    'rebounds' : IDL.Null,
    'passingYards' : IDL.Null,
    'points' : IDL.Null,
    'passesCompleted' : IDL.Null,
  });
  const LivePick = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'line' : IDL.Float64,
    'gameStatus' : GameStatus,
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'tournament' : IDL.Text,
    'sport' : Sport,
    'lineType' : LineType,
    'propType' : PropType,
    'awayMoneylineOdds' : IDL.Opt(IDL.Float64),
    'playerName' : IDL.Text,
    'homeMoneylineOdds' : IDL.Opt(IDL.Float64),
    'lineString' : IDL.Text,
    'statCategory' : StatCategory,
  });
  const LivePicksDiagnostics = IDL.Record({
    'lastFailureMessage' : IDL.Text,
    'totalFailures' : IDL.Nat,
    'lastSuccess' : Time,
    'totalAttempts' : IDL.Nat,
    'lastFailure' : Time,
    'totalSuccesses' : IDL.Nat,
    'lastAttempt' : Time,
    'numLivePicks' : IDL.Nat,
  });
  const PlayerProps = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'line' : IDL.Float64,
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'tournament' : IDL.Text,
    'sport' : Sport,
    'lineType' : LineType,
    'propType' : PropType,
    'playerName' : IDL.Text,
    'lineString' : IDL.Text,
    'statCategory' : StatCategory,
  });
  const ProjectionType = IDL.Variant({
    'userCustom' : IDL.Null,
    'algoGenerated' : IDL.Null,
  });
  const Projection = IDL.Record({
    'value' : IDL.Float64,
    'calcTime' : Time,
    'projectionType' : ProjectionType,
    'propId' : IDL.Nat,
    'isValid' : IDL.Bool,
  });
  const VerificationResult = IDL.Record({
    'verificationTime' : Time,
    'verificationSummary' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'propId' : IDL.Nat,
  });
  const PlayerPropsWithEdgesView = IDL.Record({
    'projections' : IDL.Vec(Projection),
    'verificationResults' : IDL.Vec(VerificationResult),
    'prop' : PlayerProps,
    'edges' : IDL.Vec(EdgeCalculation),
  });
  const IngestionProviderConfig = IDL.Record({
    'oddsApiKey' : IDL.Text,
    'opticOddsApiKey' : IDL.Text,
    'dailyFantasyApiKey' : IDL.Text,
  });
  const SettlementStatus = IDL.Variant({
    'active' : IDL.Null,
    'settled' : IDL.Null,
  });
  const SettlementOutcome = IDL.Variant({
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'push' : IDL.Null,
  });
  const SettleablePrediction = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'betAmount' : IDL.Opt(IDL.Float64),
    'line' : IDL.Float64,
    'gameStatus' : GameStatus,
    'odds' : IDL.Opt(IDL.Float64),
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'tournament' : IDL.Text,
    'settlementStatus' : SettlementStatus,
    'sport' : Sport,
    'lineType' : LineType,
    'propType' : PropType,
    'playerName' : IDL.Text,
    'resultValue' : IDL.Opt(IDL.Float64),
    'outcome' : IDL.Opt(SettlementOutcome),
    'lineString' : IDL.Text,
    'statCategory' : StatCategory,
  });
  const SettlementDiagnostics = IDL.Record({
    'totalSettledPredictions' : IDL.Nat,
    'lastFailureMessage' : IDL.Text,
    'totalFailedSettlements' : IDL.Nat,
    'totalSettlementAttempts' : IDL.Nat,
    'lastSuccess' : Time,
    'numSettledInLastRun' : IDL.Nat,
    'totalPendingPredictions' : IDL.Nat,
    'lastFailure' : Time,
    'lastAttempt' : Time,
    'totalSuccessfulSettlements' : IDL.Nat,
  });
  const SettlementMetrics = IDL.Record({
    'totalLost' : IDL.Nat,
    'totalPush' : IDL.Nat,
    'totalROI' : IDL.Float64,
    'totalWon' : IDL.Nat,
    'totalSettled' : IDL.Nat,
    'sevenDayWinRate' : IDL.Float64,
  });
  const OpticOddsConnectionResult = IDL.Record({
    'healthy' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'statusCode' : IDL.Opt(IDL.Nat),
    'responseBody' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActivePredictionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachRating' : IDL.Func([IDL.Nat], [IDL.Opt(CoachRatingD)], ['query']),
    'getEdgesSorted' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(EdgeCalculation)],
        ['query'],
      ),
    'getLivePicks' : IDL.Func([], [IDL.Vec(LivePick)], ['query']),
    'getLivePicksDiagnostics' : IDL.Func([], [LivePicksDiagnostics], ['query']),
    'getLivePicksLastUpdated' : IDL.Func([], [Time], ['query']),
    'getNBAPlayerProps' : IDL.Func([], [IDL.Vec(PlayerProps)], ['query']),
    'getPlayerProp' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerProps)], ['query']),
    'getPlayerPropsWithEdges' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerPropsWithEdgesView)],
        ['query'],
      ),
    'getProjection' : IDL.Func([IDL.Nat], [IDL.Opt(Projection)], ['query']),
    'getProviderConfig' : IDL.Func(
        [],
        [IDL.Opt(IngestionProviderConfig)],
        ['query'],
      ),
    'getSettleablePrediction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SettleablePrediction)],
        ['query'],
      ),
    'getSettlementDiagnostics' : IDL.Func(
        [],
        [SettlementDiagnostics],
        ['query'],
      ),
    'getSettlementMetrics' : IDL.Func([], [SettlementMetrics], ['query']),
    'getSource' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSensitivitySettings' : IDL.Func(
        [],
        [IDL.Opt(SensitivitySettings)],
        ['query'],
      ),
    'getVerificationResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VerificationResult)],
        ['query'],
      ),
    'importData' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshLivePicksInternal' : IDL.Func([], [], []),
    'register' : IDL.Func([], [], []),
    'runSettlementNow' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOrUpdateProp' : IDL.Func([PlayerProps], [], []),
    'saveProviderConfig' : IDL.Func([IngestionProviderConfig], [], []),
    'testOpticOddsConnection' : IDL.Func([], [OpticOddsConnectionResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSensitivitySettings' : IDL.Func([SensitivitySettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };