/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'notificationPreferences' : IDL.Bool,
  'name' : IDL.Text,
  'favoriteTeams' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Sport = IDL.Variant({
  'mlb' : IDL.Null,
  'nba' : IDL.Null,
  'nfl' : IDL.Null,
});
export const CoachRatingD = IDL.Record({
  'name' : IDL.Text,
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'sport' : Sport,
  'coachID' : IDL.Nat,
  'defensiveRating' : IDL.Float64,
  'lineupAdjustments' : IDL.Text,
});
export const EdgeCalculation = IDL.Record({
  'edgePercentage' : IDL.Float64,
  'calcTime' : Time,
  'propId' : IDL.Nat,
  'edgeScore' : IDL.Text,
  'isValid' : IDL.Bool,
});
export const LineType = IDL.Variant({
  'prizePicks' : IDL.Null,
  'sportsBook' : IDL.Null,
});
export const PropType = IDL.Variant({
  'playerRebounds' : IDL.Null,
  'playerPassingYards' : IDL.Null,
  'playerAssists' : IDL.Null,
  'playerPoints' : IDL.Null,
});
export const StatCategory = IDL.Variant({
  'assists' : IDL.Null,
  'rebounds' : IDL.Null,
  'passingYards' : IDL.Null,
  'points' : IDL.Null,
  'passesCompleted' : IDL.Null,
});
export const PlayerProps = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'line' : IDL.Float64,
  'team' : IDL.Text,
  'lastUpdated' : Time,
  'tournament' : IDL.Text,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'playerName' : IDL.Text,
  'lineString' : IDL.Text,
  'statCategory' : StatCategory,
});
export const ProjectionType = IDL.Variant({
  'userCustom' : IDL.Null,
  'algoGenerated' : IDL.Null,
});
export const Projection = IDL.Record({
  'value' : IDL.Float64,
  'calcTime' : Time,
  'projectionType' : ProjectionType,
  'propId' : IDL.Nat,
  'isValid' : IDL.Bool,
});
export const VerificationResult = IDL.Record({
  'verificationTime' : Time,
  'verificationSummary' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'propId' : IDL.Nat,
});
export const PlayerPropsWithEdgesView = IDL.Record({
  'projections' : IDL.Vec(Projection),
  'verificationResults' : IDL.Vec(VerificationResult),
  'prop' : PlayerProps,
  'edges' : IDL.Vec(EdgeCalculation),
});
export const IngestionProviderConfig = IDL.Record({
  'oddsApiKey' : IDL.Text,
  'opticOddsApiKey' : IDL.Text,
  'dailyFantasyApiKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachRating' : IDL.Func([IDL.Nat], [IDL.Opt(CoachRatingD)], ['query']),
  'getEdgesSorted' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(EdgeCalculation)],
      ['query'],
    ),
  'getNBAPlayerProps' : IDL.Func([], [IDL.Vec(PlayerProps)], ['query']),
  'getPlayerProp' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerProps)], ['query']),
  'getPlayerPropsWithEdges' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerPropsWithEdgesView)],
      ['query'],
    ),
  'getProjection' : IDL.Func([IDL.Nat], [IDL.Opt(Projection)], ['query']),
  'getProviderConfig' : IDL.Func(
      [],
      [IDL.Opt(IngestionProviderConfig)],
      ['query'],
    ),
  'getSource' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(VerificationResult)],
      ['query'],
    ),
  'importData' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOrUpdateProp' : IDL.Func([PlayerProps], [], []),
  'saveProviderConfig' : IDL.Func([IngestionProviderConfig], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'notificationPreferences' : IDL.Bool,
    'name' : IDL.Text,
    'favoriteTeams' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Sport = IDL.Variant({
    'mlb' : IDL.Null,
    'nba' : IDL.Null,
    'nfl' : IDL.Null,
  });
  const CoachRatingD = IDL.Record({
    'name' : IDL.Text,
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'sport' : Sport,
    'coachID' : IDL.Nat,
    'defensiveRating' : IDL.Float64,
    'lineupAdjustments' : IDL.Text,
  });
  const EdgeCalculation = IDL.Record({
    'edgePercentage' : IDL.Float64,
    'calcTime' : Time,
    'propId' : IDL.Nat,
    'edgeScore' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  const LineType = IDL.Variant({
    'prizePicks' : IDL.Null,
    'sportsBook' : IDL.Null,
  });
  const PropType = IDL.Variant({
    'playerRebounds' : IDL.Null,
    'playerPassingYards' : IDL.Null,
    'playerAssists' : IDL.Null,
    'playerPoints' : IDL.Null,
  });
  const StatCategory = IDL.Variant({
    'assists' : IDL.Null,
    'rebounds' : IDL.Null,
    'passingYards' : IDL.Null,
    'points' : IDL.Null,
    'passesCompleted' : IDL.Null,
  });
  const PlayerProps = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'line' : IDL.Float64,
    'team' : IDL.Text,
    'lastUpdated' : Time,
    'tournament' : IDL.Text,
    'sport' : Sport,
    'lineType' : LineType,
    'propType' : PropType,
    'playerName' : IDL.Text,
    'lineString' : IDL.Text,
    'statCategory' : StatCategory,
  });
  const ProjectionType = IDL.Variant({
    'userCustom' : IDL.Null,
    'algoGenerated' : IDL.Null,
  });
  const Projection = IDL.Record({
    'value' : IDL.Float64,
    'calcTime' : Time,
    'projectionType' : ProjectionType,
    'propId' : IDL.Nat,
    'isValid' : IDL.Bool,
  });
  const VerificationResult = IDL.Record({
    'verificationTime' : Time,
    'verificationSummary' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'propId' : IDL.Nat,
  });
  const PlayerPropsWithEdgesView = IDL.Record({
    'projections' : IDL.Vec(Projection),
    'verificationResults' : IDL.Vec(VerificationResult),
    'prop' : PlayerProps,
    'edges' : IDL.Vec(EdgeCalculation),
  });
  const IngestionProviderConfig = IDL.Record({
    'oddsApiKey' : IDL.Text,
    'opticOddsApiKey' : IDL.Text,
    'dailyFantasyApiKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachRating' : IDL.Func([IDL.Nat], [IDL.Opt(CoachRatingD)], ['query']),
    'getEdgesSorted' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(EdgeCalculation)],
        ['query'],
      ),
    'getNBAPlayerProps' : IDL.Func([], [IDL.Vec(PlayerProps)], ['query']),
    'getPlayerProp' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerProps)], ['query']),
    'getPlayerPropsWithEdges' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerPropsWithEdgesView)],
        ['query'],
      ),
    'getProjection' : IDL.Func([IDL.Nat], [IDL.Opt(Projection)], ['query']),
    'getProviderConfig' : IDL.Func(
        [],
        [IDL.Opt(IngestionProviderConfig)],
        ['query'],
      ),
    'getSource' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VerificationResult)],
        ['query'],
      ),
    'importData' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOrUpdateProp' : IDL.Func([PlayerProps], [], []),
    'saveProviderConfig' : IDL.Func([IngestionProviderConfig], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };