/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoachRatingD {
  'name' : string,
  'team' : string,
  'lastUpdated' : Time,
  'sport' : Sport,
  'coachID' : bigint,
  'defensiveRating' : number,
  'lineupAdjustments' : string,
}
export interface EdgeCalculation {
  'edgePercentage' : number,
  'calcTime' : Time,
  'propId' : bigint,
  'edgeScore' : string,
  'isValid' : boolean,
}
export type GameStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface IngestionProviderConfig {
  'oddsApiKey' : string,
  'opticOddsApiKey' : string,
  'dailyFantasyApiKey' : string,
}
export type LineType = { 'prizePicks' : null } |
  { 'sportsBook' : null };
export interface LivePick {
  'id' : bigint,
  'source' : string,
  'line' : number,
  'gameStatus' : GameStatus,
  'team' : string,
  'lastUpdated' : Time,
  'tournament' : string,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'awayMoneylineOdds' : [] | [number],
  'playerName' : string,
  'homeMoneylineOdds' : [] | [number],
  'lineString' : string,
  'statCategory' : StatCategory,
}
export interface LivePicksDiagnostics {
  'lastFailureMessage' : string,
  'totalFailures' : bigint,
  'lastSuccess' : Time,
  'totalAttempts' : bigint,
  'lastFailure' : Time,
  'totalSuccesses' : bigint,
  'lastAttempt' : Time,
  'numLivePicks' : bigint,
}
export interface OpticOddsConnectionResult {
  'healthy' : boolean,
  'message' : string,
  'timestamp' : Time,
  'statusCode' : [] | [bigint],
  'responseBody' : [] | [string],
}
export interface PlayerProps {
  'id' : bigint,
  'source' : string,
  'line' : number,
  'team' : string,
  'lastUpdated' : Time,
  'tournament' : string,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'playerName' : string,
  'lineString' : string,
  'statCategory' : StatCategory,
}
export interface PlayerPropsWithEdgesView {
  'projections' : Array<Projection>,
  'verificationResults' : Array<VerificationResult>,
  'prop' : PlayerProps,
  'edges' : Array<EdgeCalculation>,
}
export interface Projection {
  'value' : number,
  'calcTime' : Time,
  'projectionType' : ProjectionType,
  'propId' : bigint,
  'isValid' : boolean,
}
export type ProjectionType = { 'userCustom' : null } |
  { 'algoGenerated' : null };
export type PropType = { 'playerRebounds' : null } |
  { 'playerPassingYards' : null } |
  { 'playerAssists' : null } |
  { 'playerPoints' : null };
export interface SensitivitySettings {
  'marketAlertsEnabled' : boolean,
  'edgeThresholdPercentage' : bigint,
  'verificationRollingWindow' : VerificationRollingWindow,
}
export interface SettleablePrediction {
  'id' : bigint,
  'source' : string,
  'betAmount' : [] | [number],
  'line' : number,
  'gameStatus' : GameStatus,
  'odds' : [] | [number],
  'team' : string,
  'lastUpdated' : Time,
  'tournament' : string,
  'settlementStatus' : SettlementStatus,
  'sport' : Sport,
  'lineType' : LineType,
  'propType' : PropType,
  'playerName' : string,
  'resultValue' : [] | [number],
  'outcome' : [] | [SettlementOutcome],
  'lineString' : string,
  'statCategory' : StatCategory,
}
export interface SettlementDiagnostics {
  'totalSettledPredictions' : bigint,
  'lastFailureMessage' : string,
  'totalFailedSettlements' : bigint,
  'totalSettlementAttempts' : bigint,
  'lastSuccess' : Time,
  'numSettledInLastRun' : bigint,
  'totalPendingPredictions' : bigint,
  'lastFailure' : Time,
  'lastAttempt' : Time,
  'totalSuccessfulSettlements' : bigint,
}
export interface SettlementMetrics {
  'totalLost' : bigint,
  'totalPush' : bigint,
  'totalROI' : number,
  'totalWon' : bigint,
  'totalSettled' : bigint,
  'sevenDayWinRate' : number,
}
export type SettlementOutcome = { 'won' : null } |
  { 'lost' : null } |
  { 'push' : null };
export type SettlementStatus = { 'active' : null } |
  { 'settled' : null };
export type Sport = { 'mlb' : null } |
  { 'nba' : null } |
  { 'nfl' : null };
export type StatCategory = { 'assists' : null } |
  { 'rebounds' : null } |
  { 'passingYards' : null } |
  { 'points' : null } |
  { 'passesCompleted' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'notificationPreferences' : boolean,
  'name' : string,
  'sensitivitySettings' : SensitivitySettings,
  'favoriteTeams' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationResult {
  'verificationTime' : Time,
  'verificationSummary' : string,
  'confidenceScore' : number,
  'propId' : bigint,
}
export type VerificationRollingWindow = { 'last3Games' : null } |
  { 'seasonAverage' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActivePredictionsCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachRating' : ActorMethod<[bigint], [] | [CoachRatingD]>,
  'getEdgesSorted' : ActorMethod<[boolean], Array<EdgeCalculation>>,
  'getLivePicks' : ActorMethod<[], Array<LivePick>>,
  'getLivePicksDiagnostics' : ActorMethod<[], LivePicksDiagnostics>,
  'getLivePicksLastUpdated' : ActorMethod<[], Time>,
  'getNBAPlayerProps' : ActorMethod<[], Array<PlayerProps>>,
  'getPlayerProp' : ActorMethod<[bigint], [] | [PlayerProps]>,
  'getPlayerPropsWithEdges' : ActorMethod<
    [bigint],
    [] | [PlayerPropsWithEdgesView]
  >,
  'getProjection' : ActorMethod<[bigint], [] | [Projection]>,
  'getProviderConfig' : ActorMethod<[], [] | [IngestionProviderConfig]>,
  'getSettleablePrediction' : ActorMethod<
    [bigint],
    [] | [SettleablePrediction]
  >,
  'getSettlementDiagnostics' : ActorMethod<[], SettlementDiagnostics>,
  'getSettlementMetrics' : ActorMethod<[], SettlementMetrics>,
  'getSource' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSensitivitySettings' : ActorMethod<[], [] | [SensitivitySettings]>,
  'getVerificationResult' : ActorMethod<[bigint], [] | [VerificationResult]>,
  'importData' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshLivePicksInternal' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[], undefined>,
  'runSettlementNow' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOrUpdateProp' : ActorMethod<[PlayerProps], undefined>,
  'saveProviderConfig' : ActorMethod<[IngestionProviderConfig], undefined>,
  'testOpticOddsConnection' : ActorMethod<[], OpticOddsConnectionResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSensitivitySettings' : ActorMethod<[SensitivitySettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];