/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface IngestionProviderConfig {
    oddsApiKey: string;
    opticOddsApiKey: string;
    dailyFantasyApiKey: string;
}
export interface EdgeCalculation {
    edgePercentage: number;
    calcTime: Time;
    propId: bigint;
    edgeScore: string;
    isValid: boolean;
}
export interface PlayerPropsWithEdgesView {
    projections: Array<Projection>;
    verificationResults: Array<VerificationResult>;
    prop: PlayerProps;
    edges: Array<EdgeCalculation>;
}
export interface PlayerProps {
    id: bigint;
    source: string;
    line: number;
    team: string;
    lastUpdated: Time;
    tournament: string;
    sport: Sport;
    lineType: LineType;
    propType: PropType;
    playerName: string;
    lineString: string;
    statCategory: StatCategory;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface VerificationResult {
    verificationTime: Time;
    verificationSummary: string;
    confidenceScore: number;
    propId: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Projection {
    value: number;
    calcTime: Time;
    projectionType: ProjectionType;
    propId: bigint;
    isValid: boolean;
}
export interface UserProfile {
    notificationPreferences: boolean;
    name: string;
    favoriteTeams: Array<string>;
}
export interface CoachRatingD {
    name: string;
    team: string;
    lastUpdated: Time;
    sport: Sport;
    coachID: bigint;
    defensiveRating: number;
    lineupAdjustments: string;
}
export enum LineType {
    prizePicks = "prizePicks",
    sportsBook = "sportsBook"
}
export enum ProjectionType {
    userCustom = "userCustom",
    algoGenerated = "algoGenerated"
}
export enum PropType {
    playerRebounds = "playerRebounds",
    playerPassingYards = "playerPassingYards",
    playerAssists = "playerAssists",
    playerPoints = "playerPoints"
}
export enum Sport {
    mlb = "mlb",
    nba = "nba",
    nfl = "nfl"
}
export enum StatCategory {
    assists = "assists",
    rebounds = "rebounds",
    passingYards = "passingYards",
    points = "points",
    passesCompleted = "passesCompleted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachRating(coachId: bigint): Promise<CoachRatingD | null>;
    getEdgesSorted(invalidIncluded: boolean): Promise<Array<EdgeCalculation>>;
    getNBAPlayerProps(): Promise<Array<PlayerProps>>;
    getPlayerProp(propId: bigint): Promise<PlayerProps | null>;
    getPlayerPropsWithEdges(propId: bigint): Promise<PlayerPropsWithEdgesView | null>;
    getProjection(propId: bigint): Promise<Projection | null>;
    getProviderConfig(): Promise<IngestionProviderConfig | null>;
    getSource(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerificationResult(propId: bigint): Promise<VerificationResult | null>;
    importData(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveOrUpdateProp(prop: PlayerProps): Promise<void>;
    saveProviderConfig(config: IngestionProviderConfig): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CoachRatingD as _CoachRatingD, EdgeCalculation as _EdgeCalculation, IngestionProviderConfig as _IngestionProviderConfig, LineType as _LineType, PlayerProps as _PlayerProps, PlayerPropsWithEdgesView as _PlayerPropsWithEdgesView, Projection as _Projection, ProjectionType as _ProjectionType, PropType as _PropType, Sport as _Sport, StatCategory as _StatCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VerificationResult as _VerificationResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachRating(arg0: bigint): Promise<CoachRatingD | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachRating(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachRating(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEdgesSorted(arg0: boolean): Promise<Array<EdgeCalculation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEdgesSorted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEdgesSorted(arg0);
            return result;
        }
    }
    async getNBAPlayerProps(): Promise<Array<PlayerProps>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNBAPlayerProps();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNBAPlayerProps();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProp(arg0: bigint): Promise<PlayerProps | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProp(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProp(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerPropsWithEdges(arg0: bigint): Promise<PlayerPropsWithEdgesView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerPropsWithEdges(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerPropsWithEdges(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjection(arg0: bigint): Promise<Projection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjection(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjection(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderConfig(): Promise<IngestionProviderConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderConfig();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderConfig();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSource(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSource();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSource();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerificationResult(arg0: bigint): Promise<VerificationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationResult(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationResult(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async importData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.importData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveOrUpdateProp(arg0: PlayerProps): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOrUpdateProp(to_candid_PlayerProps_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOrUpdateProp(to_candid_PlayerProps_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProviderConfig(arg0: IngestionProviderConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProviderConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProviderConfig(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_CoachRatingD_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoachRatingD): CoachRatingD {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_LineType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LineType): LineType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerPropsWithEdgesView_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerPropsWithEdgesView): PlayerPropsWithEdgesView {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProps_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProps): PlayerProps {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectionType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectionType): ProjectionType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Projection_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Projection): Projection {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PropType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropType): PropType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StatCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatCategory): StatCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProps]): PlayerProps | null {
    return value.length === 0 ? null : from_candid_PlayerProps_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerPropsWithEdgesView]): PlayerPropsWithEdgesView | null {
    return value.length === 0 ? null : from_candid_PlayerPropsWithEdgesView_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Projection]): Projection | null {
    return value.length === 0 ? null : from_candid_Projection_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IngestionProviderConfig]): IngestionProviderConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerificationResult]): VerificationResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoachRatingD]): CoachRatingD | null {
    return value.length === 0 ? null : from_candid_CoachRatingD_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: string;
    line: number;
    team: string;
    lastUpdated: _Time;
    tournament: string;
    sport: _Sport;
    lineType: _LineType;
    propType: _PropType;
    playerName: string;
    lineString: string;
    statCategory: _StatCategory;
}): {
    id: bigint;
    source: string;
    line: number;
    team: string;
    lastUpdated: Time;
    tournament: string;
    sport: Sport;
    lineType: LineType;
    propType: PropType;
    playerName: string;
    lineString: string;
    statCategory: StatCategory;
} {
    return {
        id: value.id,
        source: value.source,
        line: value.line,
        team: value.team,
        lastUpdated: value.lastUpdated,
        tournament: value.tournament,
        sport: from_candid_Sport_n9(_uploadFile, _downloadFile, value.sport),
        lineType: from_candid_LineType_n14(_uploadFile, _downloadFile, value.lineType),
        propType: from_candid_PropType_n16(_uploadFile, _downloadFile, value.propType),
        playerName: value.playerName,
        lineString: value.lineString,
        statCategory: from_candid_StatCategory_n18(_uploadFile, _downloadFile, value.statCategory)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projections: Array<_Projection>;
    verificationResults: Array<_VerificationResult>;
    prop: _PlayerProps;
    edges: Array<_EdgeCalculation>;
}): {
    projections: Array<Projection>;
    verificationResults: Array<VerificationResult>;
    prop: PlayerProps;
    edges: Array<EdgeCalculation>;
} {
    return {
        projections: from_candid_vec_n24(_uploadFile, _downloadFile, value.projections),
        verificationResults: value.verificationResults,
        prop: from_candid_PlayerProps_n12(_uploadFile, _downloadFile, value.prop),
        edges: value.edges
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    calcTime: _Time;
    projectionType: _ProjectionType;
    propId: bigint;
    isValid: boolean;
}): {
    value: number;
    calcTime: Time;
    projectionType: ProjectionType;
    propId: bigint;
    isValid: boolean;
} {
    return {
        value: value.value,
        calcTime: value.calcTime,
        projectionType: from_candid_ProjectionType_n27(_uploadFile, _downloadFile, value.projectionType),
        propId: value.propId,
        isValid: value.isValid
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    team: string;
    lastUpdated: _Time;
    sport: _Sport;
    coachID: bigint;
    defensiveRating: number;
    lineupAdjustments: string;
}): {
    name: string;
    team: string;
    lastUpdated: Time;
    sport: Sport;
    coachID: bigint;
    defensiveRating: number;
    lineupAdjustments: string;
} {
    return {
        name: value.name,
        team: value.team,
        lastUpdated: value.lastUpdated,
        sport: from_candid_Sport_n9(_uploadFile, _downloadFile, value.sport),
        coachID: value.coachID,
        defensiveRating: value.defensiveRating,
        lineupAdjustments: value.lineupAdjustments
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mlb: null;
} | {
    nba: null;
} | {
    nfl: null;
}): Sport {
    return "mlb" in value ? Sport.mlb : "nba" in value ? Sport.nba : "nfl" in value ? Sport.nfl : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prizePicks: null;
} | {
    sportsBook: null;
}): LineType {
    return "prizePicks" in value ? LineType.prizePicks : "sportsBook" in value ? LineType.sportsBook : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerRebounds: null;
} | {
    playerPassingYards: null;
} | {
    playerAssists: null;
} | {
    playerPoints: null;
}): PropType {
    return "playerRebounds" in value ? PropType.playerRebounds : "playerPassingYards" in value ? PropType.playerPassingYards : "playerAssists" in value ? PropType.playerAssists : "playerPoints" in value ? PropType.playerPoints : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assists: null;
} | {
    rebounds: null;
} | {
    passingYards: null;
} | {
    points: null;
} | {
    passesCompleted: null;
}): StatCategory {
    return "assists" in value ? StatCategory.assists : "rebounds" in value ? StatCategory.rebounds : "passingYards" in value ? StatCategory.passingYards : "points" in value ? StatCategory.points : "passesCompleted" in value ? StatCategory.passesCompleted : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userCustom: null;
} | {
    algoGenerated: null;
}): ProjectionType {
    return "userCustom" in value ? ProjectionType.userCustom : "algoGenerated" in value ? ProjectionType.algoGenerated : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProps>): Array<PlayerProps> {
    return value.map((x)=>from_candid_PlayerProps_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Projection>): Array<Projection> {
    return value.map((x)=>from_candid_Projection_n25(_uploadFile, _downloadFile, x));
}
function to_candid_LineType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineType): _LineType {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerProps_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerProps): _PlayerProps {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PropType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropType): _PropType {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_StatCategory_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatCategory): _StatCategory {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: string;
    line: number;
    team: string;
    lastUpdated: Time;
    tournament: string;
    sport: Sport;
    lineType: LineType;
    propType: PropType;
    playerName: string;
    lineString: string;
    statCategory: StatCategory;
}): {
    id: bigint;
    source: string;
    line: number;
    team: string;
    lastUpdated: _Time;
    tournament: string;
    sport: _Sport;
    lineType: _LineType;
    propType: _PropType;
    playerName: string;
    lineString: string;
    statCategory: _StatCategory;
} {
    return {
        id: value.id,
        source: value.source,
        line: value.line,
        team: value.team,
        lastUpdated: value.lastUpdated,
        tournament: value.tournament,
        sport: to_candid_Sport_n34(_uploadFile, _downloadFile, value.sport),
        lineType: to_candid_LineType_n36(_uploadFile, _downloadFile, value.lineType),
        propType: to_candid_PropType_n38(_uploadFile, _downloadFile, value.propType),
        playerName: value.playerName,
        lineString: value.lineString,
        statCategory: to_candid_StatCategory_n40(_uploadFile, _downloadFile, value.statCategory)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    mlb: null;
} | {
    nba: null;
} | {
    nfl: null;
} {
    return value == Sport.mlb ? {
        mlb: null
    } : value == Sport.nba ? {
        nba: null
    } : value == Sport.nfl ? {
        nfl: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineType): {
    prizePicks: null;
} | {
    sportsBook: null;
} {
    return value == LineType.prizePicks ? {
        prizePicks: null
    } : value == LineType.sportsBook ? {
        sportsBook: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropType): {
    playerRebounds: null;
} | {
    playerPassingYards: null;
} | {
    playerAssists: null;
} | {
    playerPoints: null;
} {
    return value == PropType.playerRebounds ? {
        playerRebounds: null
    } : value == PropType.playerPassingYards ? {
        playerPassingYards: null
    } : value == PropType.playerAssists ? {
        playerAssists: null
    } : value == PropType.playerPoints ? {
        playerPoints: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatCategory): {
    assists: null;
} | {
    rebounds: null;
} | {
    passingYards: null;
} | {
    points: null;
} | {
    passesCompleted: null;
} {
    return value == StatCategory.assists ? {
        assists: null
    } : value == StatCategory.rebounds ? {
        rebounds: null
    } : value == StatCategory.passingYards ? {
        passingYards: null
    } : value == StatCategory.points ? {
        points: null
    } : value == StatCategory.passesCompleted ? {
        passesCompleted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
